### ISSUE TITLE
<stderr>: [grpc-default-executor-0] WARN io.grpc.netty.shaded.io.netty.util.internal.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: 08:d7:9e:98:80:ca:bc:b5

### ISSUE THREAD

**Issue by ivanzhujunwei** [googleapis/java-logging#220] opened 2020-08-24 02:22 UTC
#### Environment details

1. Specify the API at the beginning of the title. `com.google.cloud.logging`
2. OS type and version: `GCP App engine`
3. Java version: `Java 8`
4. logging version(s): `1.101.3-SNAPSHOT`

#### Steps to reproduce

  1. Followed the tutorial from here: https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-java
  2. Deployed to App Engine, this warning does not happen every time, but frequently.

#### Any additional information below
Also, not only the place implemented the gcloud logging had this warning message, other places that did not have the gcloud logging also happened to encounter this warning message. 
All of them are appearing on the logName called: `request_log` (appengine.googleapis.com%2Frequest_log)

Thanks!

![image](https://user-images.githubusercontent.com/14146339/90997283-7d9e3780-e604-11ea-9b81-3943451735fe.png)

**Comment by suraj-qlogic** [comment] 2020-09-17 06:28
@ivanzhujunwei ,Thanks for filling the issue.Looks like the ```README``` is outdated,I am try to reproduced it with ```java-logging``` with ```1.102.0``` but i am unable to reproduced and please let us know if it helps:

**pom.xml** 

```
<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>google-cloud-logging</artifactId>
	<version>1.102.0</version>
</dependency>
```

**HelloServlet.java**

```
import com.google.cloud.MonitoredResource;
import com.google.cloud.logging.LogEntry;
import com.google.cloud.logging.Logging;
import com.google.cloud.logging.LoggingOptions;
import com.google.cloud.logging.Payload;
import com.google.cloud.logging.Severity;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.PrintWriter;
import java.util.Collections;

@WebServlet(name = "helloworld", value = "")
@SuppressWarnings("serial")
public class HelloServlet extends HttpServlet {
  @Override
  public void doGet(HttpServletRequest req, HttpServletResponse resp)  {
      // Instantiates a client
      try(Logging logging = LoggingOptions.getDefaultInstance().getService()){
      // The name of the log to write to
      String logName = "my-test-log";

      // The data to write to the log
      String text = "Hello, this is testing!";

      LogEntry entry = LogEntry.newBuilder(Payload.StringPayload.of(text))
              .setSeverity(Severity.ERROR)
              .setLogName(logName)
              .setResource(MonitoredResource.newBuilder("global").build())
              .build();

      // Writes the log entry asynchronously
      logging.write(Collections.singleton(entry));
      System.out.printf("Logged: %s%n", text);
      PrintWriter out = resp.getWriter();
      out.println("Hello, world - App Engine Flexible");
    } catch (Exception e) {
      System.out.println("Exception:"+e.getCause());
    }
  }
}
// [END gae_flex_servlet]
```

**Output:**
![java-logging-output](https://user-images.githubusercontent.com/48670070/93428342-e2d00a80-f8dc-11ea-8585-01c7aca89576.jpg)

**Comment by Daniel-Sanche** [comment] 2021-02-10 22:50
I'm going to close this since it wasn't able to be reproduced. Feel free to re-open if you think it's still relevant though, and I can take a look

**Closed by Daniel-Sanche** 2021-02-10 22:50 UTC
Labels: api: logging, priority: p2, type: question
