### ISSUE TITLE
Mapping LogBack markers to Cloud logging severities

### ISSUE THREAD

**Issue by knyttl** [googleapis/java-logging#348] opened 2020-11-21 06:09 UTC
According to http://www.slf4j.org/faq.html#fatal I have prepared markers which correspond to logging levels in GCloud:

```
    private val alertMarker = MarkerFactory.getMarker("ALERT")
    private val criticalMarker = MarkerFactory.getMarker("CRITICAL")
    private val emergencyMarker = MarkerFactory.getMarker("EMERGENCY")
```

The levels are taken from: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity

Then I would like to be able to actually use this as:

```
log.error(alertMarker, "Alert message")
```

This however does not work. Is there some need to map these to the gcloud logging? I would like to be able to use up the full potential of the logging system and use all the LogSeverities.

**Comment by simonz130** [comment] 2021-07-14 00:47
We are working on implementing structured logging across logging client libraries in java/python/node/go. As part of that work, we will be implementing correct mapping of severities between Logback and Cloud Logging. This is expected to be implemented in Q3.

**Comment by simonz130** [comment] 2021-08-11 06:14
Added a label to signal that the issue is "on hold to close" as we progressing through the structured logging work.

**Comment by minherz** [comment] 2021-09-02 13:19
@knyttl, if it is still relevant, can you please elaborate your example with additional code lines and configurations.

* what logger do you use (logback, jul, etc/)?
* how do you configure it?

it is hard to provide you whether it is possible to support such conversion within the logging library without this information.
if the issue is no longer relevant, feel free to close it.

**Comment by knyttl** [comment] 2021-09-02 14:30
I followed the examples given in slf4j and google cloud logging. I don't remember more as I abandonden this approach.

**Comment by minherz** [comment] 2021-09-02 18:10
Would it be OK to close this issue then?

**Closed** 2021-09-02 18:14 UTC
Labels: type: question, external, api: logging, priority: p3, lang: java
