### ISSUE TITLE
Conflicts with Cloud Functions

### ISSUE THREAD

**Issue by knyttl** [googleapis/java-logging#428] opened 2021-02-10 07:32 UTC
#### Environment details

- OS type and version: Cloud Logging Java11 environment
- Java version: Java11

#### Steps to reproduce

Try to write any LogEntry with Java11 Cloud Function with appropriately set service account.

It will fail with: `io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 49.998533332s.` (stacktrace below). 

The very same code will work correctly with Cloud Run and the same service account.

#### Stack trace
```
https://gist.github.com/knyttl/280b465c7ab4135a41f12e77eb07efee
```

#### Minimal demonstrating example

```kotlin
import com.google.cloud.functions.HttpFunction
import com.google.cloud.functions.HttpRequest
import com.google.cloud.functions.HttpResponse
import com.google.cloud.logging.LogEntry
import com.google.cloud.logging.LoggingOptions
import com.google.cloud.logging.Payload
import com.google.cloud.logging.Severity
import java.util.Collections

class LoggingDemo : HttpFunction {
    private val logger = LoggingOptions
        .getDefaultInstance()
        .getService()

    override fun service(request: HttpRequest, response: HttpResponse) {
        val logEntry = LogEntry
            .newBuilder(Payload.StringPayload.of("message"))
            .setSeverity(Severity.INFO)
            .build()

        logger.write(Collections.singleton(logEntry))
    }
}
```

**Comment by knyttl** [comment] 2021-02-17 13:16
Can you please have a look on this, this is a blocker for us as we cannot process the logs correctly from cloudfunctions.

**Comment by Daniel-Sanche** [comment] 2021-02-19 00:14
I'm going to close this as it looks like a duplicate of https://github.com/googleapis/java-logging/issues/432

Cloud Functions aren't yet officially supported, but we're working on it. In the meantime, these docs should explain the current best practices for logging from Cloud Functions using Java: https://cloud.google.com/functions/docs/concepts/java-logging

**Closed by Daniel-Sanche** 2021-02-19 00:14 UTC
Labels: :rotating_light:, api: logging, triage me
