### ISSUE TITLE
blocking batch flow control belies async logging

### ISSUE THREAD

**Issue by benjaminp** [googleapis/java-logging#701] opened 2021-09-30 01:08 UTC
google-cloud-logging enables the blocking flow controller in the GAX batching library, going to lengths to modify the [default gapic behavior](https://github.com/googleapis/googleapis/blob/ee3c7eb3401f8de84348046b71fba7b1ac2215cf/google/logging/v2/logging_gapic.yaml#L22): https://github.com/googleapis/java-logging/blob/7b3928e1df1986bfd6fdd1197e22bcc00ce96a6d/google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/GrpcLoggingRpc.java#L168-L181

The trouble with the blocking batch flow controller is that it can block `LoggingImpl.writeAsync` and thus any application code that happens to log after the flow controller is full. (That can happen either because of too much application logging or because of a slow-down in the logging service.) Preferable behavior would be dropping the log messages that cannot be uploaded and leaving a note about dropped messages in the next batch or stderr.

(This issue is notwithstanding a recent regression described in #632. That regression occludes the problematic behavior described here by removing the GAX batcher.)

**Comment by minherz** [comment] 2021-09-30 13:52
Hello, the gax batching logic cannot be controlled from the logging library because stubs are auto-generated. There is a planned work (ETA Q1'22) to migrate the batching logic from gax to the logging library. The batching configuration will be exposed to users avoiding discrepancies.
We will review the auto-generated code to ensure that its current version is synchronized with the settings of the [gax-java](https://github.com/googleapis/gax-java).

**Comment by benjaminp** [comment] 2021-09-30 16:39
So, you're saying the code in the logging library I linked to in OP is a noop?

**Comment by minherz** [comment] 2021-10-03 17:04
I'd confirmed that the code you referenced is not auto-generated. I understand your concern about being blocked although the blocking takes place until the current batch is sent, the default GAX behavior, throwing exception seems more dangerous since it can unexpectedly crash the application.
Other mechanisms for handling errors cannot be introduced until the batching logic will be transferred into the library (see #705)

**Comment by benjaminp** [comment] 2021-10-04 02:48
Thank you for the replies. It looks like implementing #705 would provide the behavior I desire.

**Comment by minherz** [comment] 2021-10-04 10:03
One of its goals is to provide the control over batching configuration to the library users.

**Closed by minherz** 2021-10-04 10:03 UTC
Labels: type: process, api: logging, lang: java
